name: Publish JAR to GitHub Packages

on:
  push:
    branches: [ "main" ]  # Trigger on push to main (change as needed)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17  # or 11/21 as needed
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build and publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
